// server/containers/react/src/App.tsx
import { useState } from 'react'


function App() {
  const [count, setCount] = useState(0)

  return (
    <>
      <div className='container'>
        <h1>React</h1>
        <img src="https://cdn.worldvectorlogo.com/logos/react-2.svg" alt="react" className="logo" />
        <p>{count}</p>
        <button onClick={() => setCount(count + 1)}>Click me</button>
        </div>
    </>
  )
}

export default App

// server/containers/vue/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
const count = ref(0)
</script>
<template>
   <div className='container'>
          <h1>Vue</h1>
          <img src="https://cdn.worldvectorlogo.com/logos/vue-js-1.svg" alt="react" className="logo" />
          <p>{{ count }}</p>
          <button @click="count++">Click me</button>
          </div>
</template>
